version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_MAP_KEY
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
    networks:
      - network-frontend

networks:
  network-frontend:
    driver: bridge
    external: true
